[I 20180505 09:15:52 basehttp:124] "GET / HTTP/1.1" 200 1714
[I 20180505 09:15:52 basehttp:124] "GET / HTTP/1.1" 200 1714
[W 20180505 09:15:52 base:152] Not Found: /favicon.ico
[W 20180505 09:15:52 basehttp:124] "GET /favicon.ico HTTP/1.1" 404 1962
[I 20180505 09:15:52 basehttp:124] "GET / HTTP/1.1" 200 1714
[W 20180505 09:15:52 base:152] Not Found: /favicon.ico
[W 20180505 09:15:52 basehttp:124] "GET /favicon.ico HTTP/1.1" 404 1962
[I 20180505 09:15:52 basehttp:124] "GET / HTTP/1.1" 200 1714
[I 20180505 11:10:16 basehttp:124] "GET / HTTP/1.1" 200 1714
[I 20180505 11:10:17 basehttp:124] "GET / HTTP/1.1" 200 1714
[E 20180507 22:14:31 nmap_all_server:124] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 95, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:14:36 nmap_all_server:124] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 95, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:14:36 nmap_all_server:124] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 99, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:14:36 nmap_all_server:124] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 95, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:14:36 nmap_all_server:124] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 99, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:14:36 nmap_all_server:124] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 95, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:14:40 nmap_all_server:124] Telnet port Exception:192.168.5.99,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 95, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:14:44 nmap_all_server:124] Telnet port Exception:192.168.5.99,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 95, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:16:33 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:16:37 nmap_all_server:125] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:16:37 nmap_all_server:125] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:16:37 nmap_all_server:125] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:16:37 nmap_all_server:125] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:16:37 nmap_all_server:125] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:16:41 nmap_all_server:125] Telnet port Exception:192.168.5.99,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:16:45 nmap_all_server:125] Telnet port Exception:192.168.5.99,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:18:02 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:18:06 nmap_all_server:125] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:18:06 nmap_all_server:125] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:18:06 nmap_all_server:125] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:18:06 nmap_all_server:125] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:18:06 nmap_all_server:125] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:18:10 nmap_all_server:125] Telnet port Exception:192.168.5.99,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:18:14 nmap_all_server:125] Telnet port Exception:192.168.5.99,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:01 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:05 nmap_all_server:125] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:05 nmap_all_server:125] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:22:05 nmap_all_server:125] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:22:05 nmap_all_server:125] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:22:05 nmap_all_server:125] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:22:09 nmap_all_server:125] Telnet port Exception:192.168.5.99,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:13 nmap_all_server:125] Telnet port Exception:192.168.5.99,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:51 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:55 nmap_all_server:125] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:22:55 nmap_all_server:125] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:22:55 nmap_all_server:125] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:22:55 nmap_all_server:125] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:22:55 nmap_all_server:125] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:22:59 nmap_all_server:125] Telnet port Exception:192.168.5.99,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:23:03 nmap_all_server:125] Telnet port Exception:192.168.5.99,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:31:42 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:31:46 nmap_all_server:125] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:31:46 nmap_all_server:125] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:31:46 nmap_all_server:125] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:31:47 nmap_all_server:125] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:31:47 nmap_all_server:125] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:31:51 nmap_all_server:125] Telnet port Exception:192.168.5.99,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:31:55 nmap_all_server:125] Telnet port Exception:192.168.5.99,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:32:51 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:33:27 nmap_all_server:125] Telnet port Exception:192.168.5.1,22,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:33:31 nmap_all_server:125] Telnet port Exception:192.168.5.1,5022,timed out
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[E 20180507 22:33:31 nmap_all_server:125] Telnet port Exception:192.168.5.14,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:33:31 nmap_all_server:125] Telnet port Exception:192.168.5.14,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[E 20180507 22:33:31 nmap_all_server:125] Telnet port Exception:192.168.5.56,22,cannot use a string pattern on a bytes-like object
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 100, in nmap_sship
    if re.search("ssh",tm_res.lower()):
  File "/project/env/devops/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
[E 20180507 22:33:31 nmap_all_server:125] Telnet port Exception:192.168.5.56,5022,[Errno 111] Connection refused
Traceback (most recent call last):
  File "/project/devops/scanner/util/nmap_all_server.py", line 96, in nmap_sship
    tm = telnetlib.Telnet(host=ip,port=port,timeout=4)
  File "/usr/local/lib/python3.6/telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "/usr/local/lib/python3.6/telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[I 20180509 17:46:25 nmap_all_server:109] IP:192.168.131.130 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:46:25 nmap_all_server:109] IP:192.168.131.132 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:48:54 nmap_all_server:109] IP:192.168.131.130 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:48:54 nmap_all_server:109] IP:192.168.131.132 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:51:59 nmap_all_server:109] IP:192.168.131.130 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:51:59 nmap_all_server:109] IP:192.168.131.132 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:54:33 nmap_all_server:109] IP:192.168.131.130 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:54:33 nmap_all_server:109] IP:192.168.131.132 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:58:13 nmap_all_server:109] IP:192.168.131.130 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:58:14 nmap_all_server:109] IP:192.168.131.132 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:59:42 nmap_all_server:109] IP:192.168.131.130 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
[I 20180509 17:59:42 nmap_all_server:109] IP:192.168.131.132 Port:22 Server:b'ssh-2.0-openssh_6.6.1\r\n'
